const download = "/Comprime-0.1-Beta-macOS-Apple-Silicon.zip";
function Mark({ small=false }: { small?:boolean }) { return <img className={small?"mark small":"mark"} src="/comprime-icon.png" alt="Icono de Comprime"/>; }
export default function Home(){return <main>
<nav className="nav shell"><a className="brand" href="#inicio"><Mark small/><b>Comprime</b></a><div className="navlinks"><a href="#funciones">Funciones</a><a href="#privacidad">Privacidad</a><a href="#instalar">Cómo abrirla</a></div><a className="button compact" href={download}>Descargar</a></nav>
<section id="inicio" className="hero shell"><div className="eyebrow">GRATIS PARA MACOS · 0.1 BETA</div><h1>Mismas fotos.<br/><span>Mucho menos peso.</span></h1><p className="lead">Comprime carpetas completas a un peso objetivo. Compara el resultado y conserva tus originales. Todo ocurre en tu Mac.</p><div className="actions"><a className="button primary" href={download}>Descargar para macOS ↓</a><a className="button ghost" href="#instalar">Instrucciones</a></div><p className="requirements">macOS 14 o posterior · Apple Silicon · Sin cuentas · Sin publicidad</p><div className="appframe"><div className="titlebar"><Mark small/><b>Comprime</b><span>Mismas fotos. Menos peso.</span><em>● 100% local</em></div><div className="workspace"><aside><button>Abrir carpeta</button><h4>Vacaciones</h4><small>42 imágenes · 186 MB</small>{["playa.heic","paseo.jpg","hotel.webp","mapa.png"].map((x,i)=><div className="file" key={x}><i>{i+1}</i>{x}</div>)}</aside><div className="preview"><header><b>Vista previa</b><span>playa.heic</span></header><div className="photo"><label>Original</label><label>Comprimida</label><div/></div><footer><span>4,8 MB</span><b>→ 993 KB</b><strong>−79%</strong></footer></div><div className="inspector"><h3>Comprime a tu medida</h3><label>Objetivo por imagen</label><div className="pills"><span>500 KB</span><span className="active">1 MB</span><span>2 MB</span></div><label>Formato de salida</label><div className="select">Mantener original⌄</div><p>⌾ Tus originales se conservan</p><button>Comprimir 42 fotos</button></div></div></div></section>
<section id="funciones" className="section shell"><div className="eyebrow">UN TRABAJO, BIEN HECHO</div><h2>El peso correcto, sin perder el control.</h2><div className="grid"><article><span>⇲</span><h3>Objetivo por imagen</h3><p>Elige 500 KB, 1 MB, 2 MB, 5 MB o define tu propio límite.</p></article><article><span>◐</span><h3>Comparación real</h3><p>Revisa Original y Comprimida con divisor, zoom y peso final medido.</p></article><article><span>◇</span><h3>Carpetas mixtas</h3><p>JPG, JPEG, PNG, HEIC, HEIF y WebP en una sola ejecución.</p></article><article><span>⌁</span><h3>Salida segura</h3><p>Guarda en una carpeta nueva. El reemplazo avanzado crea respaldo verificado.</p></article></div></section>
<section id="privacidad" className="privacy shell"><div><div className="eyebrow">PRIVACIDAD LOCAL</div><h2>Tus fotos no salen de tu Mac.</h2><p>Comprime no tiene cuentas, servidores ni seguimiento dentro de la aplicación. Este sitio usa Vercel Web Analytics para contar visitas anónimas, sin cookies.</p></div><Mark/></section>
<section id="instalar" className="section shell"><div className="eyebrow">PRIMERA APERTURA</div><h2>Cómo abrir esta beta.</h2><div className="steps"><div><b>1</b><p>Descarga el ZIP, descomprímelo y mueve Comprime.app a Aplicaciones.</p></div><div><b>2</b><p>Si macOS muestra una advertencia, ve a Privacidad y seguridad.</p></div><div><b>3</b><p>Presiona “Abrir igualmente”. Solo se requiere la primera vez.</p></div></div></section>
<section className="cta shell"><Mark/><h2>Menos peso. El mismo recuerdo.</h2><div className="actions"><a className="button primary" href={download}>Descargar Comprime ↓</a><a className="button ghost" href="https://x.com/Sebahhgg" target="_blank" rel="noreferrer">Escríbeme en X ↗</a></div></section><footer className="shell"><span>Comprime 0.1 Beta · 2026</span><span>Procesamiento local · Estadísticas anónimas · Sin cookies</span></footer>
</main>}
